In [1]:
import pandas as pd
import numpy as np

import matplotlib as m_plt
from matplotlib import pyplot as plt

from copy import copy
from pprint import pprint

import sys
import os

import personal_plotter as p_plt

# Autoasociator

## 1. Data Generation

In [2]:
dummy_shape = (10)
dummy_data = np.identity(dummy_shape)
print(dummy_data)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### 1.1 Data Sampling

we use our dummy data generated befor as template, being the input and objetive data equal to.

In [3]:
input_data = dummy_data.copy()
objetive_data = dummy_data.copy()

## 2. Neural Network

### 2.1 Arquitecture
bla bla
#### 2.1.1 Input Layer
bla bla
#### 2.1.2 Hiden Layer
bla bla
#### 2.1.3 Output Layer
bla bla

---
___
---

### 2.2 Functions ( Training Procedure)
bla bla
#### 2.2.1 Activation Function
bla bla sigmoid

In [4]:
def sigmoid(*args):
    return 1 / (1 + np.exp(-x_val))

#### 2.2.2 Forward
bla ble

In [7]:
def forward_engine(input_data, objetive_data, layer_container, theta_container=None,kernel=sigmoid):
    if theta_container is None:
        theta_container = [ np.zeros(layer_container[ii].shape) for ii in len(layer_container)]
    else:
        pass
    
    output = [ None for _ in range(len(layer_container)) ]
    
    relative_layer = input_data.copy()
    for index in range(len(layer_container)):
            carry =  kernel((relative_layer *  layer_container[index]) + theta_container)
            output[index] = carry.copy()
            
            relative_laye = carry.copy()
    
    return output

#### 2.2.3 Gradient Derivates
bla ble

In [8]:
def d_sigmoid(*args):
    pass    

#### 2.2.4 Backward
bla ble

In [ ]:
def backward_engine(input_data, objetive_data, layer_container, theta_container=None,
                    forward_layer,
                   learning_rate=0.01, epochs=int(1e6), threashold=0.05):
    if theta_container is None:
        theta_container = [ np.zeros(layer_container[ii].shape) for ii in len(layer_container)]
    else:
        pass
    
    output = [ None for _ in range(len(layer_container)) ]
    
    relative_layer = input_data.copy()
    for index in range(len(layer_container)):
            carry =  kernel((relative_layer *  layer_container[index]) + theta_container)
            output[index] = carry.copy()
            
            relative_laye = carry.copy()
    
    return output