In [1]:
import pandas as pd
import numpy as np

import matplotlib as m_plt
from matplotlib import pyplot as plt

from copy import copy
from pprint import pprint

import sys
import os

import personal_plotter as p_plt

# Autoasociator

## 1. Data Generation

In [2]:
dummy_shape = (10,10)
dummy_data = np.ones(dummy_shape)
print(dummy_data)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 1.1 Data Sampling

we use our dummy data generated befor as template, being the input and objetive data equal to.

In [3]:
input_data = dummy_data.copy()
objetive_data = dummy_data.copy()

## 2. Neural Network

### 2.1 Arquitecture
bla bla
#### 2.1.1 Input Layer
bla bla
#### 2.1.2 Hiden Layer
bla bla
#### 2.1.3 Output Layer
bla bla

---
___
---

### 2.2 Functions ( Training Procedure)
bla bla
#### 2.2.1 Activation Function
bla bla sigmoid

In [4]:
def sigmoid(x_val=0):
    return 1 / (1 + np.exp(-x_val))

#### 2.2.2Forward
bla ble

In [5]:
def forward_engine(input_data, objetive_data, inter_layer_container, kernel=sigmoid):
    
        

SyntaxError: unexpected EOF while parsing (<ipython-input-5-bc7a7a3108bc>, line 3)